---
apiVersion: v1
kind: Pod
metadata:
  name: pod-grafana
  labels:
    app: grafana
spec:
  containers:
    - name: doug-grafana
      image: grafana/grafana:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
  volumes:
    - name: grafana-config
      configMap:
        name: grafana-configmap

...

