apiVersion: v1
kind: Pod
metadata:
  name: pod-teste-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts: 
        - mountPath: /volume-pv
          name: volume-doug
  volumes:
    - name: volume-doug
      persistentVolumeClaim:
        claimName: pvc-doug


