---
apiVersion: v1
kind: Pod
metadata:
  name: um-pod-qualquer
spec:
  containers:
    - name: contdoug
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-doug
          name: volume-pod
  volumes:
    - name: volume-pod
      hostPath:
        path: /home/douglas/volume-doug
        type: DirectoryOrCreate

...
