apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-doug
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/douglas/volume-doug"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
