apiVersion: v1
kind: Service
metadata:
  name: svc-grafana-prometheus
spec:
  type: NodePort
  ports:
    - name: grafana
      port: 3000
      nodePort: 30005
    - name: prometheus
      port: 9090
      nodePort: 30007
  selector:
    app: grafana-prometheus